#'Performs t-tests on data frames generated by re_ functions.
#'
#'Performs t-tests (from package stats) by successively pairing and comparing
#'columns from two "re_ made" data frames (compare columns with the same rank in
#'their respective data frames). Save the p-values in a data frame and produce a
#'table and plot showing the distribution of these p-values.
#'
#'@returns A list of objects containing:
#'
#'  1)"pvalues", a one column data frame compiling all the p-values resulting
#'  from the tests. (nrow = ncol(p1) = ncol(p2))
#'
#'  2)"stats", a 1 x 3 data frame containing the percentages of tests resulting
#'  in a p-value lower than 0.001, 0.01 and 0.05
#'
#'  3)"plot", an optional ggplot2 graph showing the distribution of p-values as
#'  a plot of density, histogram or both.
#'
#'@param p1,p2  (input: data frames from re_ functions) p1 and p2 inputs must be
#'  two data frames generated from re_ functions representing the two
#'  populations that the user wants to compare. p1 and p2 need to have the same
#'  number of columns and it is recommended to generate them using the same re_
#'  function (either re_boot or re_gauss) and same settings (notably n and
#'  boot.n). (Note: p1 and p2 respectively feed x and y in the test function.
#'  The order is important e.g. for alternative = "greater".)
#'@param do.plot (input: TRUE or FALSE) Specifies if a plot of the result has to
#'  be generated (TRUE) or not (FALSE). The package ggplot2 is needed if do.plot
#'  = TRUE.
#'@param density (input: TRUE or FALSE) Specifies if the plot is a density plot
#'  (TRUE) or not (FALSE). Note: density and histogram can be combined in one
#'  plot.
#'@param histogram (input: TRUE or FALSE) Specifies if the plot is a histogram
#'  plot (TRUE) or not (FALSE).Note: density and histogram can be combined in
#'  one plot.
#'@param fill.color (input: a vector of length 4 containing only characters
#'  referring to R colors) Specifies the colors used to fill the 0 to 0.001,
#'  0.001 to 0.01, 0.01 to 0.05, 0.05 to +Inf sections (in this order) of the
#'  density plot (density = T) or histogram plot (histogram = T, density = F).
#'@param ... Allow to pass specific instructions to the test function (e.g.
#'  alternative = "greater", paired = T, etc.).
#'
#' @examples
#'# With p1 and p2, two data frames generated by a re_ function (either re_gauss
#'# or re_boot) and same parameters. Attached re_Pop1 and re_Pop2 data frames
#'# have been generated by re_gauss with n=1000, a purposely small n, too small
#'# for proper analyses but allowing for quicker processing time for the purpose
#'# of this demonstration.
#'
#'#Only produces result data frames (no plot)
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, do.plot=FALSE)
#'
#'#Produces an hybrid density + histogram plot (+ result data frames)
#'roll_ttest(p1=re_Pop1, p2=re_Pop2)
#'
#'#Produces a density plot (+ result data frames)
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, histogram = FALSE)
#'
#'#Produces a histogram plot (+ result data frames)
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=FALSE, histogram = TRUE)
#'
#'#Pass specific instructions to t.test function (package stats)
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=FALSE, histogram = TRUE, alternative = "greater")
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=FALSE, histogram = TRUE, paired = TRUE)
#'
#'#Customized plot colors for density
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=TRUE, histogram =TRUE,
#'fill.color=c("green","deepskyblue","blue","yellow"))
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=TRUE, histogram =FALSE,
#'fill.color=c("green","deepskyblue","blue","yellow"))
#'#and histogram
#'roll_ttest(p1=re_Pop1, p2=re_Pop2, density=FALSE, histogram =TRUE,
#'fill.color=c("green","deepskyblue","blue","yellow"))
#'@export

roll_ttest = function(p1, p2, do.plot=T, density=T, histogram=T, fill.color=c("dodgerblue4","dodgerblue2","deepskyblue2","red"), ...) {

#----------------------
#General requirement checks
if(missing(p1)) stop("You need to specify an input for p1. Provide a data frame generated by a re_ function (re_gauss or re_boot).")
if(missing(p2)) stop("You need to specify an input for p2. Provide a data frame generated by a re_ function (re_gauss or re_boot).")
if(ncol(p1)!=ncol(p2)) stop("Sorry, you need to perform this test with the same number of replicated populations (i.e. ncol(p1)==ncol(p2), same n within re_gauss or re_boot).")
if(do.plot!=T && do.plot!=F) stop("Invalid input for do.plot argument. Possible input: TRUE (default) or FALSE")
if(do.plot==T && !requireNamespace("ggplot2", quietly = TRUE)) stop("You need to install ggplot2 to use rerollR plotting system.")
if(density!=T && density!=F) stop("Invalid input for density argument. Possible input: TRUE (default) or FALSE")
if(histogram!=T && histogram!=F) stop("Invalid input for histogram argument. Possible input: TRUE (default) or FALSE")
if(density==F && histogram==F && do.plot==T) stop("At least one of the following argument (density, histogram) need to be set to TRUE if do.plot==T.")
if(!is.vector(fill.color) || !is.character(fill.color) || length(fill.color) != 4) stop("fill.color can only be a vector of length==4 containing characters referring to colors (e.g. 'white', '#000000').")

x<-y<-p.value<-count<-fill<-NULL #create null variables to clear CMD check generated caused by ggplot2 data call structure and after_stat variables
#----------------------
#Core code
#t test between col one after the other
tres <-  data.frame(last=1:1) #create the df to store ttest results
k=1
repeat{
  tres[,"last"]<- NA
  tres[,ncol(tres)]<-t.test(x=p1[,c(k)],y=p2[,(k)],...)$p.value
  names(tres)[ncol(tres)] <- k
  k=k+1
  if(ncol(p1)<k){break}
}

#Create a list summarizing the percentages of p value bellow 0.05, 0.01 and 0.001 (the ifelse(is.null) is here to force the return of a 0 instead of a numeric(0) when the number of a given category is 0))
res_list<- data.frame("p0.001"= length(tres[,tres <= 0.001])/length(tres)*100, "p0.01"= length(tres[,tres <= 0.01])/length(tres)*100, "p0.05"= length(tres[,tres <= 0.05])/length(tres)*100)# create a list of statistics about the tests
ttres<-data.frame(p.value=t(tres))

#----------------------
#Plot results
if (do.plot==T) {

  d <- with(density(t(tres), from=0), data.frame(x, y))
  #conditional density parameters to improve readability for low p values and prevent density curve to start at x<0
  if(max(d$x)<0.001 & min(d$x)<0) {d <- with(density(ttres$p.value, from=0, to=0.001), data.frame(x, y))}
  if(min(d$x)<0) {d <- with(density(ttres$p.value, from=0), data.frame(x, y))}
  if(max(d$x)<0.001) {d <- with(density(ttres$p.value, to=0.001), data.frame(x, y))}

  #scale density to the max of the histogram if combined density + histogram plot
  if(histogram==T) d[,"y"]<- d[,"y"]/max(d$y)*100*max(proportions(table(trunc(ttres$p.value*10^3)/10^3)))

  #fill grading for histogram when density==F
  if(density==F && histogram == T) {
    rescol <- ttres
    rescol[,"fill"] <- "D"
    if(any(rescol$p.value <= 0.05))rescol[rescol$p.value <= 0.05,]$fill <- "C"
    if(any(rescol$p.value <= 0.01))rescol[rescol$p.value <= 0.01,]$fill <- "B"
    if(any(rescol$p.value <= 0.001))rescol[rescol$p.value <= 0.001,]$fill <- "A"
  }

  #Plot
  resplot<- ggplot2::ggplot(data = d, mapping = ggplot2::aes(x = x, y = y)) +

    {if(density==T)ggplot2::geom_area(data=d, mapping = ggplot2::aes(x = x, y=ifelse(x >= 0.05, y, 0)), na.rm=T, fill =  fill.color[4], alpha=0.75)} +
    {if(density==T)ggplot2::geom_area(data=d, mapping = ggplot2::aes(x = x, y=ifelse(x <= 0.05 & x >= 0.01, y, 0)), na.rm=T, fill = fill.color[3])} +
    {if(density==T)ggplot2::geom_area(data=d, mapping = ggplot2::aes(x = x, y=ifelse(x <= 0.01 & x >= 0.001, y, 0)), na.rm=T, fill = fill.color[2])} +
    {if(density==T)ggplot2::geom_area(data=d, mapping = ggplot2::aes(x = x, y= ifelse(x <= 0.001 & x >= 0, y, 0)), na.rm=T, fill = fill.color[1])} +
    {if(density==T)ggplot2::geom_line(data=d, mapping = ggplot2::aes(x=x, y=y), na.rm=T)} +

    {if(density==T && histogram == T)ggplot2::geom_histogram(data = ttres, ggplot2::aes(x=p.value, ggplot2::after_stat(count/sum(count)*100)), boundary=0, binwidth = 0.001, color="grey50", fill="white", alpha=0.1, na.rm = T)} +
    {if(density==F && histogram == T)ggplot2::geom_histogram(data = rescol, ggplot2::aes(x=p.value, ggplot2::after_stat(count/sum(count)*100), fill=fill), boundary=0, binwidth = 0.001, color="black", na.rm=T)} +
    {if(density==F && histogram == T)ggplot2::scale_fill_manual(breaks= c("A","B","C","D"), values = fill.color)} +
    {if(density==F && histogram == T)ggplot2::guides(fill="none")} +

    #label 0.05
    ggplot2::annotate("segment", x = 0.05, xend = 0.05, y = 0, yend = d[which(abs(d$x-0.05)==min(abs(d$x-0.05))),which( colnames(d)=="y" )]+max(d$y)*0.04)+
    ggplot2::annotate("text", x = 0.05, y = d[which(abs(d$x-0.05)==min(abs(d$x-0.05))),which( colnames(d)=="y" )]+max(d$y)*0.09, label= (paste0(c(res_list$p0.05),"%")), cex = 5)+

    #label 0.01
    ggplot2::annotate("segment", x = 0.01, xend = 0.01, y = 0, yend = d[which(abs(d$x-0.01)==min(abs(d$x-0.01))),which( colnames(d)=="y" )]+max(d$y)*0.04)+
    ggplot2::annotate("text", x = 0.01, y = d[which(abs(d$x-0.01)==min(abs(d$x-0.01))),which( colnames(d)=="y" )]+max(d$y)*0.09, label= (paste0(c(res_list$p0.01),"%")), cex = 5)+

    #label 0.001
    ggplot2::annotate("segment", x = 0.001, xend = 0.001, y = 0, yend = d[which(abs(d$x-0.001)==min(abs(d$x-0.001))),which( colnames(d)=="y" )]+max(d$y)*0.04)+
    ggplot2::annotate("text", x = 0.001, y = d[which(abs(d$x-0.001)==min(abs(d$x-0.001))),which( colnames(d)=="y" )]+max(d$y)*0.09, label= (paste0(c(res_list$p0.001),"%")), cex = 5)+

    #specific label when all pvalues <= 0.001
    {if(all(ttres$p.value <= 0.001)) ggplot2::annotate("text", x = 0.025, y= max(d$y)/2, label= (paste("All p-values are below 0.001")), cex = 4)}+

    #Axis and theme
    {if(density==T)ggplot2::scale_x_continuous(limits=c(0, ifelse(max(d$x) < 0.05, 0.05, max(d$x))))}+
    {if(density==F)ggplot2::scale_x_continuous(limits=c(0, ifelse(max(ttres) < 0.05, 0.05, max(ttres))))}+
    ggplot2::theme_bw()+
    {if(density==T && histogram==F)ggplot2::labs(title= paste("Student's t-tests (",deparse(substitute(p1)), " Vs ", deparse(substitute(p2)),")"), y="Density", x= "p-value")}+
    {if(histogram==T)ggplot2::labs(title= paste("Student's t-tests (",deparse(substitute(p1)), " Vs ", deparse(substitute(p2)),")"), y="Percentage (%)", x= "p-value")}

} #plot end

#----------------------
#Return results
ifelse(do.plot==T, all_res<-list(pvalues= ttres, stats=res_list,  plot = resplot), all_res<-list(pvalues= ttres, stats=res_list, plot = "No plot generated. do.plot set to F."))
return(all_res)

} #function end
